---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Beis.HelpToGrow.Voucher.Web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: Beis.HelpToGrow.Voucher.Web
    spec:
      containers:
        - name: Beis.HelpToGrow.Voucher.Web
          image: proxytechnology/Beis.HelpToGrow.Voucher.Web:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
  selector:
    matchLabels:
      app: Beis.HelpToGrow.Voucher.Web
---
apiVersion: v1
kind: Service
metadata:
  name: Beis.HelpToGrow.Voucher.Web
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: Beis.HelpToGrow.Voucher.Web   
