name: CI Deploy FunctionApp QA

on:
 workflow_dispatch:
 
env:
  AZURE_FUNCTIONAPP_NAME: htg-qa-voucher-function-app
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'BEIS.HelpToGrow.Voucher.FunctionApp'

jobs:
  build-qa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build "BEIS.HelpToGrow.Voucher.FunctionApp/Beis.HelpToGrow.Voucher.FunctionApp.csproj" --no-restore

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Publish Function App for Release
      run: dotnet publish "BEIS.HelpToGrow.Voucher.FunctionApp/Beis.HelpToGrow.Voucher.FunctionApp.csproj" --configuration Release --output ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output

    - name: 'Deploy to Azure Function App'
      uses: azure/functions-action@v1
      with:
        app-name: '${{ env.AZURE_FUNCTIONAPP_NAME }}'
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

    - name: Azure logout
      run: |
        az logout